apiVersion: v1
kind: Secret
metadata:
  name: "harbor-registry"
  namespace: harbor
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "ak1aekVwdFhpZTNJZE9HSg=="
  REGISTRY_REDIS_PASSWORD: ""
