version: '3.8'

services:
  sonarqube9:
    image: sonarqube:9.9-community
    container_name: sonarqube9  # 自定义容器名称
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://10.0.13.169:5432/sonarqube9"
      SONAR_JDBC_USERNAME: "postgres"
      SONAR_JDBC_PASSWORD: "0ngkg.IYgzb3mfcl"
    ports:
      - "9001:9000"
    #network_mode: host  # 设置网络模式为 host
    restart: always
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
