version: '3.8'

services:
  sonarqube9:
    image: sonarqube:9.9.8-community
    container_name: sonarqube9  # 自定义容器名称
    environment:
      SONARQUBE_JDBC_URL: "jdbc:postgresql://192.168.0.3:5432/sonar"
      SONARQUBE_JDBC_USERNAME: "postgres"
      SONARQUBE_JDBC_PASSWORD: "1"
    ports:
      - "9000:9000"  # 暴露 PostgreSQL 的默认端口
    #network_mode: host  # 设置网络模式为 host
    restart: always
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
