apiVersion: v2
appVersion: 1.15.0
description: A Helm chart for banzaicloud/bank-vaults Vault operator
home: https://banzaicloud.com/products/bank-vaults/
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: vault-operator
sources:
- https://github.com/hashicorp/vault
- https://github.com/banzaicloud/bank-vaults
- https://github.com/banzaicloud/banzai-charts
type: application
version: 1.15.2
