# Source: loggie/templates/loggie-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loggie-rolebinding-loggie-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loggie-role-loggie-collector
subjects:
  - kind: ServiceAccount
    name: loggie-collector
    namespace: logging
