# Source: loggie/templates/loggie-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: loggie
    instance: loggie-collector
  name: loggie-collector
  namespace: logging
spec:
  selector:
    matchLabels:
      app: loggie
      instance: loggie-collector
  template:
    metadata:
      labels:
        app: loggie
        instance: loggie-collector
    spec:
      containers:
        - args:
            - -meta.nodeName=$(HOST_NAME)
            - -config.system=/opt/loggie/loggie.yml
            - -config.pipeline=/opt/loggie/pipeline/*.yml
            - -log.jsonFormat=false
            - -log.level=info
          env:
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: hub.c.163.com/loggie/loggie:v1.0.0
          name: loggie
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
              
            - mountPath: /var/log/pods
              name: podlogs
            - mountPath: /var/lib/kubelet/pods
              name: kubelet
            - mountPath: /var/lib/docker
              name: docker
            - mountPath: /opt/loggie/loggie.yml
              name: loggie-config
              subPath: loggie.yml
            - mountPath: /opt/loggie/pipeline
              name: pipeline
            - mountPath: /data/
              name: registry

      serviceAccountName: loggie-collector
      nodeSelector:
        {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - loggie
            topologyKey: kubernetes.io/hostname
      tolerations:
        []
      volumes:
        - hostPath:
            path: /var/log/pods
            type: DirectoryOrCreate
          name: podlogs
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: kubelet
        - hostPath:
            path: /var/lib/docker
            type: DirectoryOrCreate
          name: docker
        - configMap:
            defaultMode: 384
            name: loggie-config-loggie-collector
          name: loggie-config
        - hostPath:
            path: /data/loggie-loggie-collector
            type: DirectoryOrCreate
          name: registry
        - emptyDir: {}
          name: pipeline
  updateStrategy:
    type: RollingUpdate
