apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin-svc
  namespace: iov-dev01
  labels:
    app: xxl-job-admin
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: xxl-job-admin
