#kubernetes v1.22+
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxl-job-admin-ingress
  namespace: iov-dev01
spec:
  ingressClassName: nginx-vpc
  rules:
  - host: xxl-job-admin-dev01.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: xxl-job-admin-svc
            port:
              number: 8080
