---
# Ansible EC2 external inventory script settings
# https://docs.ansible.com/ansible/latest/plugins/inventory/aws_ec2.html

plugin: aws_ec2

# regions: all
# regions: us-east-1,us-west-1,ca-central-1
# regions: cn-north-1
regions:
  - ap-northeast-1
  - us-east-1
# regions_exclude:
#   - us-gov-west-1
#   - cn-north-1

keyed_groups:
  # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags
