---
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
all:
  # hosts:
  #   localhost:
  #     ansible_sudo: false
  #     ansible_connection: local
  #     ansible_python_interpreter: python
  children:
    app:
      children:
        tag_comp_app:
        local:
    bastion:
      children:
        tag_comp_bastion:
    worker:
      children:
        tag_comp_worker:
    cron:
      children:
        tag_comp_cron:
    elasticsearch:
      children:
        tag_comp_elasticsearch:
    tag_comp_app:
    tag_comp_worker:
    tag_comp_cron:
    tag_comp_bastion:
    tag_comp_devops:
    tag_comp_elasticsearch:
    tag_env_dev:
    tag_env_stage:
    tag_env_prod:
# vars:
#   # Tell Ansible to use Python 3 on target machines
#   ansible_python_interpreter: /usr/bin/python3
