apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: kube-system
resources:
  - dh-deployment.yml
  - dh-service.yml
  
bases:
  # - ./src
patchesStrategicMerge:
  # - patch.yml
