# Source: skywalking/templates/oap-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-skywalking
  labels:
    app: release-name
    chart: "skywalking-4.2.0"
    release: "release-name"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-skywalking
subjects:
  - kind: ServiceAccount
    name: release-name-skywalking-oap
    namespace: tracing
