---
# defaults file for nginx-app

# Ports that the app listens on
nginx_app_proxy_ports:
  - 4000

# Log format: main | json
nginx_app_log_format: main

# Enable SSL
nginx_app_ssl_on: false
nginx_app_ssl_certificate_path: /etc/nginx/ssl/server.crt
nginx_app_ssl_certificate_key_path: /etc/nginx/ssl/server.key

nginx_app_limit_req_on: false
nginx_app_limit_req_zone: "$binary_remote_addr zone=foo:10m rate=1r/s"
nginx_app_limit_req: "zone=foo burst=5 nodelay"

# Default template locations, defined as variables so they can be overridden
nginx_app_systemd_override_template: etc/systemd/system/nginx.service.d/override.conf.j2
nginx_app_nginx_conf_template: etc/nginx/nginx.conf.j2
nginx_app_default_conf_template: etc/nginx/conf.d/default.conf.j2
nginx_app_localhost_conf_template: etc/nginx/conf.d/localhost.conf.j2
