---
# Set SSM parameter store entries for app
#
# This reads values from the Ansible vault and sets corresponding entries in
# AWS SSM Parameter Store.
#
# It runs locally on the Ansible machine
#
# ansible-playbook -v -u $USER --extra-vars "env=$ENV comp=app" playbooks/$APP/config-app-ssm.yml -D

- name: Create SSM parameter store entries
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    org_unique: cogini
    app_name: foo
    key_prefix: "/{{ org_unique }}"
  vars_files:
    - "../../vars/{{ app_name }}/{{ env }}/common.yml"
    - "../../vars/{{ app_name }}/{{ env }}/app-secrets.yml"
  tasks:
    - name: Create SSM parameter store entry for app secret_key_base
      aws_ssm_parameter_store:
        name: "{{ key_prefix }}/{{ app_name }}/{{ env }}/{{ comp }}/endpoint/secret_key_base"
        description: "App endpoint secret_key_base"
        value: "{{ secret_key_base }}"
        string_type: "SecureString"
        key_id: "{{ aws_key_id }}"
        region: "{{ aws_region }}"
        # overwrite_value: "always"
    - name: Create SSM parameter store entry for app erlang_cookie
      aws_ssm_parameter_store:
        name: "{{ key_prefix }}/{{ app_name }}/{{ env }}/{{ comp }}/erlang_cookie"
        description: "App erlang_cookie"
        value: "{{ erlang_cookie }}"
        string_type: "SecureString"
        key_id: "{{ aws_key_id }}"
        region: "{{ aws_region }}"
        # overwrite_value: "always"
