apiVersion: v1
kind: Service
metadata:
  name: nvdmirror-svc
  namespace: ci
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  selector:
    app: nvdmirror
