---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-webui-id01-embeddings
  namespace: online
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-webui-id01-models
  namespace: online
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-webui-id01-outputs
  namespace: online
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-csi
