---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-webui-id01-data
  namespace: online
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: local-path
