---
# defaults file for iptables-http

# Port that app listens on
iptables_http_app_port_http: 4000
iptables_http_app_port_https: 4001

# HTTP public port
iptables_http_external_port_http: 80
iptables_http_external_port_https: 443

# Whether to open external ports
iptables_http_open_http: false
iptables_http_open_https: false

# Whether to redirect external port to listen port
iptables_http_redirect_http: false
iptables_http_redirect_https: false

# Whether to rate limit inbound HTTP connections
iptables_http_rate_limit_http: false
iptables_http_rate_limit_https: false

# Rate limit options
iptables_http_rate_limit_options_http: "-m hashlimit --hashlimit-name HTTP --hashlimit 5/minute --hashlimit-burst 10 --hashlimit-mode srcip --hashlimit-htable-expire 300000"
iptables_http_rate_limit_options_https: "-m hashlimit --hashlimit-name HTTPS --hashlimit 5/minute --hashlimit-burst 10 --hashlimit-mode srcip --hashlimit-htable-expire 300000"
