#仅限于缓存用途，没有持久存储
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: redis
  labels:
    app: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        name: redis
        app: redis-cache
      annotations:
        #disable istio sidecar injection
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: redis
        image: redis:6.0
        resources:
          # keep request = limit to keep this container in guaranteed class
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: "/etc/redis"
      volumes:
        - name: redis-config
          configMap:
            name: redis-etc-configmap
            #Add ConfigMap data to a specific path in the Volume
            items:
            - key: redis.conf
              path: redis.conf
